# Generated by Django 5.2.8 on 2025-11-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Household', 'Household'), ('Snacks', 'Snacks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('liter', 'liter'), ('piece', 'piece')], max_length=20),
        ),
    ]
