# Generated by Django 5.2.8 on 2025-11-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slot',
            field=models.CharField(max_length=100),
        ),
    ]
